### ISSUE TITLE
implement -i for trash-put

### ISSUE THREAD

**Issue by goodevilgenius** [andreafrancia/trash-cli#10]
trash-put allows the -i flag for gnu rm compatibility, however, it's silently ignored.

It would be useful to actually support interactive moving to the trash.

**Comment by Ganton** [comment]
Hi, I have similar problems. 

> Patch welcome.
Could this issue be reopened so that people are able to know that this issue exists?

**Comment by andreafrancia** [comment]
From the [0.21.5.25 release](https://github.com/andreafrancia/trash-cli/releases/tag/0.21.5.25) trash-put honors the `-i` option.
Example:

```
$ touch foo
$ trash-put -i foo
trash-put: trash regular empty file 'foo'? y
$ 
```

You can add `alias trash-put='trash-put -i'` to your `.bashrc`
