### ISSUE TITLE
man trash says "see also trash-restore" instead of "restore-trash"

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [andreafrancia/trash-cli#101]
v. 0.12.9.14-2, the latest under Ubuntu 16.04:
man trash sez:
"see also trash-restore"
not "restore-trash" like it should.

**Comment by andreafrancia** [comment]
The right place to signal bugs about trash-cli packaged by Ubuntu is the Ubuntu bug tracker: https://bugs.launchpad.net/ubuntu/+source/trash-cli/

Please consider that the version you are talking about is very old, is from 2012, unfortunately seems that Ubuntu is still using a old version in its distribution. The current version is 0.17.1.14.
