### ISSUE TITLE
How to restore a file programmatically?

### ISSUE THREAD

**Issue by mvasin** [andreafrancia/trash-cli#102]
Please provide an example how to restore a file programmatically in the readme.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
What do you mean with "programmatically"? Do you have an example?

**Comment by mvasin** [comment]
Hi! 4 years later I’m not sure what did I mean, maybe there were no cli command at the time (more likely), or I wanted to restore file in python without invoking the shell (less likely). Let me close the issue.
