### ISSUE TITLE
trash-restore does not restore all trashes

### ISSUE THREAD

**Issue by mhham** [andreafrancia/trash-cli#104]
I am using trash-cli-git(AUR: trash-cli-git 591.36ae6da-1) version 0.17.1.14.

I am trashing files from `/mnt/sda1` and `~`. They are sent to `/mnt/sda1/.Trash-1000` and `~/.local/share/Trash` respectively.

Listing them works fine:

    $ trash-list
    2017-09-03 15:39:58 ~/toremove2.txt
    2017-09-03 15:39:40 /mnt/sda1/DOCUMENTS/toremove.txt
    
Emptying the trash with `trash-empty` and file by file with `trash-rm` work fine.

However when restoring the files with `trash-restore` all files are not restored. If I am in the `~` directory only files from `~/.local/share/Trash` are suggested to be restored. Similarly, if I am in `/mnt/sda1` only files from `/mnt/sda1/.Trash-1000` are suggested. 

Could you instead make `trash-restore` work globally, as for the others commands ? 

Cheers, and thanks for the great work !

**Comment by jpbegin** [comment]
I second. I've trashed a file that was there: `/opt/hidden/suite/hidden/lib/i965_drv_video.so` mounted on `/`. The `df -h /opt/hidden/suite/hidden/lib/` command was returning the following:

```
root@jpb-ubuntu16-64:/opt/broadsign/suite/bsp/lib# df -h /opt/hidden/suite/hidden/lib/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       117G  5.5G  105G   5% /
```

The `trash-list` command was showing me the file but I wasn't seeing it with `restore-trash`. Cause of you @mhham I been able to find that the trashed file was located in `~/.local/share/Trash/files` so I been able to `cp` that file to its previous location. Thanks a lot by the way.

**Comment by andreafrancia** [comment]
Too see trashed files from everywhere use:

```
trash-restore /
```
