### ISSUE TITLE
More intutive commands instead of separate executables

### ISSUE THREAD

**Issue by kronos29296** [andreafrancia/trash-cli#106]
This is more of a suggestion but instead of having separate executables they can be called by arguments to the same command trash.

An example would be to use `trash restore` instead of `trash-restore`. The man pages can also be merged for all the commands to improve discoverability. This would be similar to how git works. Even though every git command is a separate executable we can call them without the '-'. When I started using trash-cli finding the appropriate man pages was harder than just typing `man trash` since the command itself was only `trash`.

**Comment by UnicodeAlt255** [comment]
What if there is a path called `restore`? What would `trash restore` do?
