### ISSUE TITLE
trash-put creates a .Trash directory without sticky bit, trash-list complains about it

### ISSUE THREAD

**Issue by db-inf** [andreafrancia/trash-cli#109]
I installed trash-cli 0.12.9.14-2 from the Ubuntu (Xenial) software centre, and I am very happy with it.

On my hard disks I have "_.Trash_" directories properly set up, but I have no "_.Trash_" directory on a tmpfs file system, mounted at "_/media/ramdisk_", that I use as ramdisk.

While configuring the spacefm file manager to use trash-put when pressing [Delete], I called `trash-put` on a file on that ramdisk: `trash-put` created the proper directory structure "_/media/ramdisk/.Trash/1000_", but without sticky bit on "_/media/ramdisk/.Trash_". `trash-list` complains about this : "_TrashDir skipped because parent not sticky: /media/ramdisk/.Trash/1000_"

It is no problem for me, because in the end I configured spacefm to delete files on the ramdisk immediately with `rm`, instead of trashing them; a ramdisk is not meant to keep files alive anyway. But it still is something worth reporting.

**Comment by andreafrancia** [comment]
Please install a newer version of trash-cli. The 0.12.9.14-2  version is from 2012. Try installing it from pip as explained in the README.
