### ISSUE TITLE
ImportError: cannot import name put

### ISSUE THREAD

**Issue by imyxh** [andreafrancia/trash-cli#111]
I get this error when trying to trash a file.

    Traceback (most recent call last):
      File "/usr/bin/trash", line 4, in <module>
        from trashcli.cmds import put as main
    ImportError: cannot import name put

**Comment by lalten** [comment]
Apparently it doesn't mix well with the `apt` version. Uninstall all versions with `apt purge` and `pip uninstall`, then use the way provided in the readme: `easy_install trash-cli`, which works.
