### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by oltodosel** [andreafrancia/trash-cli#112]
Files with long names make trash-put gobble all available CPU and freeze.

Interrupted with ctrl+c output. 
> lom@kom:~/o$ /usr/bin/python trash-put /home/lom/500px/111/http:--coolhousez.net-wp-content-uploads-2014-07-decoration-ideas-enchanting-home-architecture-and-front-porch-decoration-using-round-white-front-porch-pillar-along-with-black-roof-tile-front-porch-awning-and-light-grey-wood-siding-astonishing-pictu.jpg         
> ^CTraceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 459, in persist_trash_info
>     self.atomic_write(dest, content)
>   File "/usr/lib/python3.6/site-packages/trashcli/fs.py", line 58, in atomic_write
>     0o600)
> OSError: [Errno 36] File name too long: '/home/lom/.local/share/Trash/info/http:--coolhousez.net-wp-content-uploads-2014-07-decoration-ideas-enchanting-home-architecture-and-front-porch-decoration-using-round-white-front-porch-pillar-along-with-black-roof-tile-front-porch-awning-and-light-grey-wood-siding-astonishing-pictu.jpg_61016.trashinfo'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "trash-put", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 21, in main
>     ).run(sys.argv)
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 68, in run
>     trashcan.trash_all(args)
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 246, in trash_all
>     self.trash(arg)
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 280, in trash
>     trashed_file = trash_dir.trash(file)
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 401, in trash
>     content)
>   File "/usr/lib/python3.6/site-packages/trashcli/put.py", line 459, in persist_trash_info
>     self.atomic_write(dest, content)
> KeyboardInterrupt

I understand that's fs limit, in my case of 255 symbols; but maybe there's an option to reduce infinite attempts to a reasonable number in this while? https://github.com/andreafrancia/trash-cli/blob/5abecd53e1d84f2a5fd3fc60d2f5d71e518826c5/trashcli/put.py#L428

Consider adding something like `if index>1000:break`

**Comment by elundmark** [comment]
I've also noticed this, any thoughts on a fix for this? Makes scripting very tedious...

**Comment by andreafrancia** [comment]
Fixed with bbba723
Duplicated of #166
