### ISSUE TITLE
Alias bypassing

### ISSUE THREAD

**Issue by vstepaniuk** [andreafrancia/trash-cli#114]
https://github.com/andreafrancia/trash-cli/blob/master/README.rst#but-sometimes-i-forget-to-use-trash-put-really-cant-i

> Then, if you really want to use rm, simply prepend **a slash** to bypass the alias:
\rm file-without-hope

should be **a backslash**.

Also I think that there are better ways to bypass alias to recommend (e.g. `/bin/rm` or `command rm`), which besides that avoid the slash-backslash confusion.

**Comment by andreafrancia** [comment]
Thank you
