### ISSUE TITLE
It's hassle to find the number of file that I want to restore

### ISSUE THREAD

**Issue by hrsma2i** [andreafrancia/trash-cli#117]
If there are so many files in Trash, It's too hassle to find the number. Is there any easier way I could designate the file?

**Comment by hrsma2i** [comment]
I can do this. I just do `trash-restore | grep $FILE_NAME`

**Comment by jpggithub** [comment]
You can restore files within the files trashed today with :

export DateGrep=$(date +%Y-%m-%d) && trash-restore |grep $DateGrep

The documentation could give this kind of examples for the users?
