### ISSUE TITLE
restore from trash doens't work when manually creating .trashinfo  file

### ISSUE THREAD

**Issue by nateshmbhat** [andreafrancia/trash-cli#121]
I have tried to put the file to be deleted into the Trash/files folder and manually writing the .trashinfo file in the /Trash/info . But the trashinfo file doesn't seem to work properly and so it doens't show the "restore from trash" option in the Trash when opened in the file manager . 

How can i fix this ? I have tried to fix this a lot . Please help ......
(this is not an issue in ur code obviously , im just asking for help )

**Comment by andreafrancia** [comment]
There is a spec that describe exactly what to put inside a .trashinfo file: https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html

If you don't post the content of your handcraft .trashinfo file is impossible to tell what is wrong.
