### ISSUE TITLE
Questions (sorry - I could find no other way of asking)

### ISSUE THREAD

**Issue by ghost** [andreafrancia/trash-cli#126]
Hello!

1) Will this work with Cinnamon's trashcan?

If yes, then

2) Can I restore something - something deleted via the CLI - via the GUI (the desktop trashcan)?

**Comment by andreafrancia** [comment]
1. If Cinnnamon follow the trash specs [1] yes.
2. If Cinnnamon follow the trash specs [1] yes. 

Reading the cinnamon code [2] it seems that it uses `gio` for trashcan, so I think it should be compatible with the trash specs.

[1] https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html
[2] https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/trash%40cinnamon.org/applet.js
