### ISSUE TITLE
Mention where is the trash located on macOS in the readme

### ISSUE THREAD

**Issue by GabLeRoux** [andreafrancia/trash-cli#127]
Hey there, I've been using this for a long time, but never had to restore anything until today. After reading the readme, I realized the trash folder isn't the same as the one used by MacOS, but I feel this is not clear enough in the readme.

> It uses the same trashcan used by KDE, GNOME, and XFCE, but you can invoke it from the command line (and scripts).

I went to `~/.Trash` (macOS's default trash) and saw nothing, my hearth stopped working for a few seconds, but then I realized I had a time machine (backup hdd), and finally figured out where to find the trash used by `trash-cli` :)

* `trash-cli` version `0.17.1.14`
* OS: `macOS High Sierra 10.13.6 17G65 x86_64`
* installation method: `brew install trash-cli`

## How to reproduce

```bash
brew install trash-cli
cd ~/
touch test
trash test
ls -la ~/.Trash
```

Result:

```
total 0
drwx------    2 gableroux  staff    64 24 Sep 10:12 .
drwxr-xr-x+ 225 gableroux  staff  7200 24 Sep 10:13 ..
```

Die a bit inside while questioning your existence in the universe, then see what actually happens:

```bash
touch test
trash -v test
```
```
trash: Volume of file: /
trash: Trash-dir: /Users/gableroux/.local/share/Trash from volume: /
trash: 'test' trashed in ~/.local/share/Trash
```

So everything is fine. I think it would still be worth mentioning where the trash is by default on macOS in the readme 😊

**Comment by alexreg** [comment]
Very good point. I still don't see a note about this in the README, to be fair... Except the indirect one, perhaps ("It uses the same trashcan used by KDE, GNOME, and XFCE"). Would support for the macOS trash be possible? I'd really like that, personally.

**Comment by andreafrancia** [comment]
Closed by https://github.com/GabLeRoux/trash-cli/commit/a7899ce124d033f6bfdb8d3d77a0c97e84f8911f
