### ISSUE TITLE
trash-put: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by kaysond** [andreafrancia/trash-cli#130]
I'm having some issues trashing a file. Here's the verbose output:

```
trash-put: Volume of file: /var/www/files
trash-put: Trash-dir: /home/administrator/.local/share/Trash from volume: /home
trash-put: Trash-dir: /var/www/files/.Trash/1000 from volume: /var/www/files
trash-put: Failed to trash 20180630_164404.jpg in /var/www/files/.Trash/1000, because :[Errno 1] Operation not permitted: '/var/www/files/.Trash/1000/info'
trash-put: Trash-dir: /var/www/files/.Trash-1000 from volume: /var/www/files
trash-put: Failed to trash 20180630_164404.jpg in /var/www/files/.Trash-1000, because :[Errno 1] Operation not permitted: '/var/www/files/.Trash-1000/info'
trash-put: cannot trash regular file '20180630_164404.jpg'
```

I suspect the problem is because its on a volume that I share between multiple users, so I've created the `.Trash` directory with user `www-root` and group `www-data` (and sticky bit), which is how I grant access to users. But I think trash doesn't like putting files into a shared trash where the current user isn't the owner? I have no problem creating files in the files and info directories with `touch`

**Comment by kaysond** [comment]
pinging @andreafrancia

**Comment by andreafrancia** [comment]
Hi @kaysond, thank you for your patience.
I've prepared a new release of trash-cli that is more clearer in error messages.
Please check if it helps you.

I'm closing this issue but feel free to comment below and I will reopen it.
