### ISSUE TITLE
Problem with symlinks and btrfs subvolumes

### ISSUE THREAD

**Issue by ghost** [andreafrancia/trash-cli#131]
I have a problem with `app-misc/trash-cli-0.17.1.14_p20170816` on a Gentoo Linux system.

I have two btrfs subvolumes: `/` and `/mnt/storage`.

Under `/home/fturco` (which belongs to the first subvolume) I have several symlinks targeting directories under `/mnt/storage` (the second subvolume). For example `/home/fturco/documents` points to `/mnt/storage/documents`.

If I delete a document with `trash-put` it goes into `/mnt/storage/.Trash-1000`, but `trash-list` doesn't show anything. Also, `trash-empty` seems to be ineffective as it doesn't clean anything under `/mnt/storage/.Trash-1000`.

Is this a bug with trash-cli or a problem with my setup?

**Comment by ejpcmac** [comment]
Hi @fturco, I think this issue is related to #56. I’ve hit the same problem using ZFS: outside of the dataset where your home belongs, it seems `trash-cli` has some difficulties to work properly.

**Comment by twome** [comment]
Exactly the same problem accessing a Windows hard drive through, for example, `/mnt/g` using WSL

**Comment by andreafrancia** [comment]
Hi @ghost,
  I don't know what can be the problem.
The only suggestion I can give to you is update your version fo trash-cli. The version that you are using is from five years ago.

If you know how to modify Python code you can try to add this debug print line and send us the results:

```
diff --git a/trashcli/list.py b/trashcli/list.py
index 725b5ce..8538cf5 100644
--- a/trashcli/list.py
+++ b/trashcli/list.py
@@ -69,6 +69,7 @@ class ListCmd:
         for event, args in trash_dirs:
             if event == trash_dir_found:
                 path, volume = args
+                print("Trash directory found: {}".format(path))
                 trash_dir = TrashDirReader(self.file_reader)
                 for trash_info in trash_dir.list_trashinfo(path):
                     self._print_trashinfo(volume, trash_info, extractor, show_files)
```

**Comment by andreafrancia** [comment]
Hi @ghost, I've created a tool for diagnose problems like yours. Please install the latest version 0.22.8.21, launch this command `trash-list --debug-volumes` and send me the output.

**Comment by andreafrancia** [comment]
Related to https://github.com/andreafrancia/trash-cli/issues/245
Solved in latest version.
