### ISSUE TITLE
Automatic Purging

### ISSUE THREAD

**Issue by sungdzda** [andreafrancia/trash-cli#136]
I'd like the system to automatically delete trash files that are more than 30 days old. Is this accomplishable with trash-cli or should I use another tool like Autotrash?

Thank you.

**Comment by eloyesp** [comment]
I've just read that the command `trash-empty` accept an optional argument:

> To remove files that have been in the trash more than a given number of
> days, use 'trash-empty x', 'x' representing the number of days.

So a cron job with `trash-empty 30` should do the trick.
