### ISSUE TITLE
Problem deleting files beginning with minus

### ISSUE THREAD

**Issue by flyingrhinonz** [andreafrancia/trash-cli#137]
I'm calling trashcli from ranger to delete a file called:   -01.mp3 .
Usage: trash [OPTION]... FILE...
trash: error: no such option: -0
(END)

This appears to be a bug in transcli, at least in the version I have.

trash --version
trash 0.12.9.14

ranger --version
ranger version: ranger-master 1.9.1
Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Locale: None.None

**Comment by tari** [comment]
Putting `--` before the positional arguments should do the trick, eg

```
trash-put -- -01.mp3
```

This pattern usually indicates all following options are positional arguments, and that appears to be the case with `optparse` as used here (not documented, but in a quick experiment it works with Python 3.6- I assume it will for 2.7 as well).

**Comment by flyingrhinonz** [comment]
Oops, didn't see the text in 'trash --help' , only read the man page which is incomplete.
Resolved using '--' argument on command line.
