### ISSUE TITLE
help me, I had rm my leader's dataset!!!

### ISSUE THREAD

**Issue by GH1995** [andreafrancia/trash-cli#138]
Two weeks ago, my leader has a dataset in his `home` folder, then , I try to make a link to my `home` folder with `ln -sf /home/leader/dataset /home/my/dataset`. And, it's failed because too many file about six millions images in the folder. So, I just `rm` the link.

Today, when I type the `trash-empty`, I delete leader's a half of dataset!!!!  

**He's planning to fire me !** :cry:  :cry: :sob: :sob:

![cry](https://s2.ax1x.com/2019/02/20/k2yCZT.png)
![cry](https://s2.ax1x.com/2019/02/20/k2yPdU.jpg)
![cry](https://s2.ax1x.com/2019/02/20/k2ypLV.png)

**Comment by ratijas** [comment]
F

**Comment by antofthy** [comment]
That just shows that this package is has not be completely thought out and thoroughly tested.
Nor does it look like it is being maintained!

**Comment by GH1995** [comment]
@antofthy Thank you. Fortunately, our group has backups. Trash-cli cannot handle links to folders containing millions of files.

**Comment by antofthy** [comment]
> @antofthy Thank you. Fortunately, our group has backups. Trash-cli cannot handle links to folders containing millions of files.

Well that is good to hear.  But it does give me some major cause for worry.   Though I have been unable to reproduce the problem.  See the link above for my current findings (which is pitifully minimal)

I am also not a developer of trash-cli, just a system admin looking for trashcan solutions, and what problems they have.

**Comment by GH1995** [comment]
@andreafrancia this is a bug

**Comment by andreafrancia** [comment]
> @andreafrancia this is a bug

Prove it!

I can't reproduce the bug.

```
$ mkdir -p temp
$ touch temp/{a,b,c}
$ ln -s temp foo
$ trash-put foo
$ trash-empty
$ ls temp/
a  b  c
```

**Comment by andreafrancia** [comment]
@antofthy 
> That just shows that this package is has not be completely thought out and thoroughly tested.

Prove it. Provide reproducible steps that the show bug exists. We don't need this type of contribution.
