### ISSUE TITLE
'trash *' leaves behind the hidden files

### ISSUE THREAD

**Issue by ghost** [andreafrancia/trash-cli#139]
I'm trying to clear a directory using the command 'trash *' in a script but it doesn't remove the hidden files starting with '.'

I can remove them with 'trash .*' but it would be a lot simpler to just issue the command 'trash *' to clear all the files.

**Comment by matiaskotlik** [comment]
rm works like this as well, maybe it is better to leave it like this.

**Comment by Carlossuss** [comment]
I see that mv also works the same way. I never noticed before. I guess it must be a feature then. Thanks.

**Comment by matiaskotlik** [comment]
it's due to the way globbling works, not mv, rm, or trash. theres an option for it somewhere that you can stick in your bashrc if you don't like it.

**Comment by antofthy** [comment]
Try this magic...
`trash .? .??* *`

**Comment by andreafrancia** [comment]
You need to use
```
trash .*
```

It's a shell thing, it does not depends from trash-cli
