### ISSUE TITLE
easy_install was deprecated from Python

### ISSUE THREAD

**Issue by evandrocoan** [andreafrancia/trash-cli#140]
1. https://bugs.launchpad.net/ubuntu/+source/python-setuptools/+bug/1774419
1. https://askubuntu.com/questions/1040392/easy-install-command-not-found

How to install this package, then?

1. https://github.com/andreafrancia/trash-cli/issues/111 ImportError: cannot import name put

**Comment by andreafrancia** [comment]
The `easy_install` replacement is `pip`.
Just use:
```
pip install trash-cli
```
