### ISSUE TITLE
Change trash directory

### ISSUE THREAD

**Issue by jcguu95** [andreafrancia/trash-cli#148]
This is a duplicate question to this post three years ago (https://github.com/andreafrancia/trash-cli/issues/66), but it was closed without further discussion.

## Problem
Currently the trashes are thrown to `$HOME/.local/share/Trash`, and I'd like it to be replaced by `$HOME/.trash`. Is it possible?

## Version
`$ trash --version`
`trash 0.17.1.14`

**Comment by antofthy** [comment]
Also if you are the system administrator, you may want to clean older trash from OTHER USERS!
Which means it would be nice to set the directory path, rather than the HOME environment variable.

**Comment by jcguu95** [comment]
Solved! It seems like this project has been abandoned, so I did it myself:
> Simply change any "~/.local/share/Trash" to the directory you want.

I don't know python.. there should be a better way to do it. If any, please let me know. I will fork one out and lets move there ;D
