### ISSUE TITLE
trash-list and trash-empty cannot exit 

### ISSUE THREAD

**Issue by rysterzhu** [andreafrancia/trash-cli#152]
When the program is completed, it will not be able to exit normally, even if ctrl+C

**Comment by AkashKrDutta** [comment]
Can you elaborate on this? Maybe a short way to reproduce the above behaviour?

**Comment by rysterzhu** [comment]
sorry, I can't reproduce this problem, it may a system issue.

**Comment by p-kolacz** [comment]
I have the same problem, trash-list prints a list of trashed file and freezes. Ctrl+C doesn't work, I have to SIGKILL it.
