### ISSUE TITLE
trash-reset and trash-list to show trash files from custom trash directories

### ISSUE THREAD

**Issue by AkashKrDutta** [andreafrancia/trash-cli#153]
Since we have a feature of putting trash files into a custom directory, it would be a complete solution only when we are able to pull back from those directories as well.
Some thing like:
```
$ trash-list --trash-dir /custom/.Trash
$ trash-reset --trash-dir /custom/.Trash
```

**Comment by AkashKrDutta** [comment]
WIP from my side for this.

**Comment by JasonAn** [comment]
is there any update on this?

**Comment by andreafrancia** [comment]
With commit f11df22ffac87102289fa7dbac955a484133bd1c trash-list learnt a new option: `--trash-dir`.
We don't have a `trash-reset` command
