### ISSUE TITLE
warning of cross-spawn

### ISSUE THREAD

**Issue by richenlin** [andreafrancia/trash-cli#155]
warning trash-cli > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead

**Comment by andreafrancia** [comment]
@richenlin this is not the project you are looking for.

You may want to open an issue on the javascript trash-cli: https://github.com/sindresorhus/trash-cli/issues
