### ISSUE TITLE
use mtab in stead of fstab

### ISSUE THREAD

**Issue by sharethewisdom** [andreafrancia/trash-cli#159]
trash-list gets stuck indefinitely because of this. Why on earth is `/etc/fstab` chosen over `/etc/mtab`?

https://en.wikipedia.org/wiki/Mtab

I have automounting entries like this in fstab:

```
UUID=dd89d271-776a-426a-826d-9f4d7056fc6a /mnt/caddy ext4 nodev,nosuid,noexec,rw,noatime,data=ordered,noauto,nofail,x-systemd.automount,x-systemd.device-timeout=20,x-systemd.idle-timeout=2min 0 0
```

**Comment by andreafrancia** [comment]
Since version 0.20.11.23 trash-cli use [psutil](https://github.com/giampaolo/psutil) which correctly recognizes all present partitions.
