### ISSUE TITLE
trash-rm doesn't recognize strings containing square brackets "[]".

### ISSUE THREAD

**Issue by derrend** [andreafrancia/trash-cli#162]
I'm trying to delete torrents automatically but trash-rm doesn't recognize strings with square brackets in them, eg "[720p]".
Is there a known way to overcome this issue?

**Comment by andreafrancia** [comment]
You need to escape the square brackets enclosing them in square bracket:
```
$ touch '[720p]'
$ trash-put '[720p]'
$ trash-list
2021-05-20 22:43:44 /Users/andrea/trash-cli/[720p]
$ trash-rm '[[]720p[]]'
$ trash-list
```
