### ISSUE TITLE
"No files trashed from current dir" error

### ISSUE THREAD

**Issue by Gim6626** [andreafrancia/trash-cli#165]
I get "No files trashed from current dir" error on latest (installed from repo) trash-cli. Here is how I get it:
1. Create file:
`$ touch foofoo`
2. Move file to trash:
`$ trash foofoo`
3. Try to restore:
```
$ trash-restore foofoo 
No files trashed from current dir ('/home/dmitriy/hacking/trash-cli')
```
4. Check if file is really in trash:
```
$ trash-list | grep foofoo
2020-05-02 20:28:23 /home/dmitriy/hacking/trash-cli/foofoo
```

I've got simplest partitions setup - only one partition on root:
```
$ df
Filesystem     1K-blocks      Used Available Use% Mounted on
udev             3990984         0   3990984   0% /dev
tmpfs             806940      1732    805208   1% /run
/dev/sda1      464186104 367334332  73202648  84% /
tmpfs            4034700    585984   3448716  15% /dev/shm
tmpfs               5120         4      5116   1% /run/lock
tmpfs            4034700         0   4034700   0% /sys/fs/cgroup
tmpfs             806940        24    806916   1% /run/user/1000
```

Could anybody help with it? I'm true fan of this software, but this bug is very annoying.

**Comment by Gim6626** [comment]
Same with `trash-cli` version 0.17.1.14_3 on macOS

**Comment by Hund** [comment]
I have version 0.17.1.14 (on Gentoo) and it straight up deletes files from me. The last trashed file that I can restore is from the beginning of June.
