### ISSUE TITLE
Any active fork

### ISSUE THREAD

**Issue by soraxas** [andreafrancia/trash-cli#171]
Is there any active fork for this project? It doesn't seems like it's being maintained nor are the PRs being reviewed

**Comment by elovin** [comment]
I don't know about an active fork but maybe you could use the gio tool in glib2 which has a trash flag

**Comment by a-vrma** [comment]
Yeah gio works well enough for me. It can't restore unless you install gvfs too though.

**Comment by jxu** [comment]
Your best bet is to contact the author Andrea Francia directly. He may be willing to let some contributors have more maintenance responsibilities.

**Comment by andreafrancia** [comment]
Today I have accepted and merged some pull request and published a new version https://pypi.org/project/trash-cli/0.20.11.7/

**Comment by crazy-matt** [comment]
This one seems maintained: https://github.com/soraxas/trash-cli
Big thanks to @andreafrancia for this tools btw

**Comment by elovin** [comment]
@soraxas since there has been a new release, can we close this issue ?

**Comment by soraxas** [comment]
For sure, thanks @andreafrancia for maintaining this nice tool!
