### ISSUE TITLE
trash-empty failed to delete owned read-only files

### ISSUE THREAD

**Issue by oxalica** [andreafrancia/trash-cli#173]
For files/directories with permission like 0555 (r-xr-xr-x), they can be moved into trash-bin but cannot be deleted by `trash-empty`.
Maybe we need to `chmod` to add write permission if possible before `rm`.

**Comment by andreafrancia** [comment]
Can't reproduce.

```
vagrant@buster:~$ touch foo && chmod -w foo && ls -lad foo && trash-put foo
-r--r--r-- 1 vagrant vagrant 0 Jun  2 11:07 foo
vagrant@buster:~$ trash-list
2021-06-02 11:07:37 /home/vagrant/foo
vagrant@buster:~$ trash-empty
vagrant@buster:~$ trash-list
vagrant@buster:~$ trash-put --version
trash-put 0.21.5.20
```

Maybe you are using an old version. Install the new version with `pip install trash-put`
