### ISSUE TITLE
Problem trashing with verbose option

### ISSUE THREAD

**Issue by maicardi** [andreafrancia/trash-cli#18]
Se uso trash-put con l'opzione "verbose", il tuo script mi da un errore relativo a file non esistente e lamenta di non poterlo cestinare:

>  # trash-put -v prova.txt 
> trash-put: Failed to trash prova.txt in /media/array/.Trash/0, because :topdir should be a directory: /media/array/.Trash/0
> trash-put: `prova.txt' trashed in /media/array/.Trash-0 

Se, però, poi analizzo il cestino, quel file sembrerebbe esser stato correttamente cestinato: 

> # trash-list | grep prova.txt
> 
> 2013-05-06 14:34:22 /media/array/tmp/prova.txt

il file non è più infatti nella posizione ove si trovava:

> # ls prova.txt
> 
> ls: impossibile accedere a prova.txt: File o directory non esistente

Se non si specifica l'opzione --verbose non si ha nessun messaggio d'errore.

Sembra legato ad un uso da una parte di ~/.Trash-0 e dall'altra ~/.Trash/0 (che non esiste).

**Comment by andreafrancia** [comment]
Credo che ti stia dicendo che '/media/array/.Trash/0' non è una directory, dato che non esiste ripiega su .Trash-0 e funziona.

**Comment by maicardi** [comment]
Uhm... Sono passati più 3 anni e mezzo dal mio post... devo riprovare.

Grazie cmq di avermi risposto.

Buon Natale.

**Comment by maicardi** [comment]
Al momento in realtà non riesco a riprovare...

Su Ubuntu 16.10 installando la versione 0.12.9.14-2:

```
$ trash-list 
Errore di segmentazione (core dump creato)

$ trash-rm tmp1cTHia 
Errore di segmentazione (core dump creato)

$ trash -v foo
trash: found unusable .Trash dir (should be a dir): /.Trash
trash: Failed to trash foo in /.Trash/1000, because :[Errno 13] Permission denied: '/.Trash'
trash: Failed to trash foo in /.Trash-1000, because :[Errno 13] Permission denied: '/.Trash-1000'
trash: cannot trash regular empty file `foo'

$ mkdir -p ~/.Trash/1000

$ trash -v foo
trash: found unusable .Trash dir (should be a dir): /.Trash
trash: Failed to trash foo in /.Trash/1000, because :[Errno 13] Permission denied: '/.Trash'
trash: Failed to trash foo in /.Trash-1000, because :[Errno 13] Permission denied: '/.Trash-1000'
trash: cannot trash regular empty file `foo'
```

**Comment by maicardi** [comment]
No, non par essere un problema di packaging Ubuntu.

`
$ sudo easy_install trash-cli
Searching for trash-cli
Reading https://pypi.python.org/simple/trash-cli/
Downloading https://pypi.python.org/packages/c7/95/ceda4a06c0a8e6b57ded4a7f0a3fc9a22f443f755f06c4e562fbab5dddbe/trash-cli-0.12.9.14.tar.gz#md5=79135954bbe5d0c806d298c38e3e0527
Best match: trash-cli 0.12.9.14
Processing trash-cli-0.12.9.14.tar.gz
Writing /tmp/easy_install-NHTZzo/trash-cli-0.12.9.14/setup.cfg
Running trash-cli-0.12.9.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-NHTZzo/trash-cli-0.12.9.14/egg-dist-tmp-QoSTGi
/usr/lib/python2.7/dist-packages/setuptools/command/egg_info.py:203: UserWarning: tag_svn_revision is deprecated and will not be honored in a future release
  "tag_svn_revision is deprecated and will not be honored "
zip_safe flag not set; analyzing archive contents...
Moving trash_cli-0.12.9.14.post0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding trash-cli 0.12.9.14.post0 to easy-install.pth file
Installing restore-trash script to /usr/local/bin
Installing trash-put script to /usr/local/bin
Installing trash-list script to /usr/local/bin
Installing trash-rm script to /usr/local/bin
Installing trash script to /usr/local/bin
Installing trash-empty script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/trash_cli-0.12.9.14.post0-py2.7.egg
Processing dependencies for trash-cli
Finished processing dependencies for trash-cli
marco@rolly:/tmp$ trash
trash        trash-empty  trash-list   trash-put    trash-rm     
marco@rolly:/tmp$ trash-list 
bash: /usr/bin/trash-list: File o directory non esistente
marco@rolly:/tmp$ ls /usr/local/bin/
acdcli      multiping    pip3           pyrsa-decrypt-bigfile  pyrsa-keygen    pyrsa-verify   serve  trash-empty  trash-rm
acd_cli     multisystem  pip3.5         pyrsa-encrypt          pyrsa-priv2pub  rackup         tilt   trash-list
acd_cli.py  pip          pyrsa-decrypt  pyrsa-encrypt-bigfile  pyrsa-sign      restore-trash  trash  trash-put
$ restore-trash 
Errore di segmentazione (core dump creato)
$ /usr/local/bin/restore-trash foo
Errore di segmentazione (core dump creato)
$ /usr/local/bin/trash-list 
Errore di segmentazione (core dump creato)
`

**Comment by andreafrancia** [comment]
Mi puoi dire che versione di python hai?

**Comment by maicardi** [comment]
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2

**Comment by andreafrancia** [comment]
Quella che riscontri dovrebbe essere la issue #52, ho committato oggi la soluzione ( https://github.com/andreafrancia/trash-cli/commit/0c3f3bfc1de5ba59f951dd0a107cd9e72c6e42b8 )

**Comment by andreafrancia** [comment]
Ho pubblicato la versione "0.16.12.26" su PyPI, se fai `sudo easy_install trash-cli` dovrebbe scaricartela e risolvere il problema. Ti prego di confermare se puoi.

**Comment by maicardi** [comment]
Confermo che con la nuova versione il programma funziona. Grazie

2016-12-26 19:21 GMT+01:00 Andrea Francia <notifications@github.com>:

**Comment by maicardi** [comment]
Scusa se scrivo tramite risposta email ma sono via e non posso loggarmi su
github...

Ho notato che se provo a trash-are dei file fuori della mia home ~ (ad
esempio da /tmp) trash me li inserisce in /.Trash/1000/files nella root del
device... è normale? come mai accade?

2016-12-26 19:21 GMT+01:00 Andrea Francia <notifications@github.com>:

**Comment by andreafrancia** [comment]
È normale, trash-cli cerca sempre di spostare il file nella trash dir che sta sulla stessa partizione del file cestinato. Probabilmente la tua /tmp sta su una partizione diversa da quella di home.

**Comment by maicardi** [comment]
Hai ragione, che sciocco scusa... :-D

2016-12-27 19:14 GMT+01:00 Andrea Francia <notifications@github.com>:
