### ISSUE TITLE
Translation: What does `really can't I` mean in README?

### ISSUE THREAD

**Issue by CyrusYip** [andreafrancia/trash-cli#181]
Hi, @andreafrancia . `trash-cli` is awesome. I translated the README into simplified Chinese just now. I almost finished it. I intend to submit a pull request after I finish it.

The only sentence that I did not understand is `But sometimes I forget to use trash-put, really can't I?`. Does the sentence mean `But sometimes I forget to use trash-put, how can I avoid forgetting to use trash-put?`

**Comment by andreafrancia** [comment]
I'm not a native english speaker, I meant `But sometimes I forget to use trash-put, really can't I make the rm alias?`

**Comment by CyrusYip** [comment]
Thanks for clarifying the sentence. I finally finished the translation.
