### ISSUE TITLE
installation instructions for ubuntu

### ISSUE THREAD

**Issue by jonas-frey** [andreafrancia/trash-cli#186]
The installation command `pip install trash-cli` doesn't work on ubuntu 20.04, use `pip3 install trash-cli` instead. Moreover, contrary to debian, the .deb package is called `python-pip3`, not `python-pip`.

**Comment by andreafrancia** [comment]
On Ubuntu 20.04 I have found `python3-pip`. I updated the README accordingly in 3fd217d2f8964ebcc15f725d2625b4cb2c098126
