### ISSUE TITLE
Configure trash folders with other functions

### ISSUE THREAD

**Issue by gcoimbra** [andreafrancia/trash-cli#187]
> With commit [d34551f](https://github.com/andreafrancia/trash-cli/commit/d34551f7a5574aef2c3b9eccff2b94c0c4e890ed) trash-put learned a --trash-dir option that can be used to specify the trash directory to be used as destination.
> 
> You can force the use of a specific trash typing:
> 
> ```
> trash-put --trash-dir /.Trash-1000 file-to-be-trashed
> ```
> 
> Please check it out and tell if it works for you.

I have now compiled the version because the Distris simply do not record it.

The variable works quite well, but you can't view this data with "trash-list", the default folder is always used.

So the variable would have to be implemented for the other functions as well. :)

_Originally posted by @Anagastes in https://github.com/andreafrancia/trash-cli/issues/35#issuecomment-709271853_

So it would be nice to have this on trash-empty, for example.

**Comment by andreafrancia** [comment]
With commit f11df22ffac87102289fa7dbac955a484133bd1c trash-list learnt a new option: `--trash-dir`.
