### ISSUE TITLE
trash-list option doesn't work: --trash-dir=...

### ISSUE THREAD

**Issue by akharrou** [andreafrancia/trash-cli#189]
**Describe the bug**
`trash-list --trash-dir="$HOME/.Trash"` doesn't work, it prints nothing instead of listing the trashed items.

**trash-cli version**
trash 0.20.12.26

**Operating system:**
 - OS: macOs

**To Reproduce**
```
trash-put --trash-dir="$HOME/.Trash" -- foo.txt      # works 
trash-list --trash-dir="$HOME/.Trash"                # doesn't work; doesn't show trashed files
```

**Expected behavior**
It should show the trashed files, and in this specific example at least: '`foo.txt`'.

**Comment by mattbui** [comment]
`trash-list` doesn't have `--trash-dir` option, I requested this feature in #196. My workaround for now: `find /your/trash/dir/info/*.trashinfo -exec cat {} +`

**Comment by andreafrancia** [comment]
With commit f11df22ffac87102289fa7dbac955a484133bd1c trash-list learnt a new option: `--trash-dir`.
