### ISSUE TITLE
User defined trash folder in trash-list

### ISSUE THREAD

**Issue by mattbui** [andreafrancia/trash-cli#196]
**Is your feature request related to a problem? Please describe.**
Currently, `trash-put` have the `--trash-dir` option which is extremely useful for my use case, which I have limited access to a volume eg: `/mnt/a`  so the default `trash-put` will not work as it cannot create `/mnt/a/.Trash-$uid`. But there's no option for specifying `trash-dir` with `trash-list`

**Describe the solution you'd like**
`trash-list --trash-dir /my/trash/path`

**Describe alternatives you've considered**
`find /mnt/a/mydir/.Trash/info/*.trashinfo -exec cat {} +`

**Comment by andreafrancia** [comment]
With commit f11df22ffac87102289fa7dbac955a484133bd1c trash-list learnt a new option: `--trash-dir`.
