### ISSUE TITLE
trash-restore > Invalid entry

### ISSUE THREAD

**Issue by newcanopies** [andreafrancia/trash-cli#199]
Thank you for this package!

**Describe the bug**

entering the exact filename to be restored, (following the tutotial) returns Invalid entry and does not restore the file. 

**trash-cli version**
debian install: trash-put 0.17.1.14

**Operating system:**
 - OS: Ubuntu 20.04

**To Reproduce**

~/WS$ trash ros_foxy.rosinstall
~/WS$ trash-restore
   0 2021-04-30 12:45:21 /home/user/WS/ros_foxy.rosinstall
What file to restore [0..0]: **ros_foxy.rosinstall**
**Invalid entry**

**Expected behavior**
restore trashed file, but file is not restored.

**Comment by andreafrancia** [comment]
You need to enter the index, in this case "0" (zero).

**Comment by newcanopies** [comment]
One more confusing bit please. Both of these commands work to delete files and directories: 

$ `trash foo`
$` trash-put foo`

Is there a any difference under the hood?
Mille grazie

**Comment by andreafrancia** [comment]
No, there is no any difference between trash-put and trash. "trash" was the name of "trash-put" before the [generic name issue](https://github.com/andreafrancia/trash-cli/blob/master/docs/about-the-generic-naming-issue.txt).

I'm thinking about removing `trash` and leave only `trash-put`.

About using the alias check this: https://github.com/andreafrancia/trash-cli/#can-i-alias-rm-to-trash-put

**Comment by newcanopies** [comment]
Very interesting back-story, thank you for sharing. I do hope the interest in this great package can be regained!

For me as a user, `trash` is most effective. 

Thank you very much!
