### ISSUE TITLE
feature request: make `trash` a subcommand multiplexer instead of an overload of `trash-put`

### ISSUE THREAD

**Issue by pabs3** [andreafrancia/trash-cli#201]
I think the trend of having a short primary command name that is a multiplexer for different subcommands is very ergonomic on the command-line. For example `git` has `git commit`, `git push` etc.

I think it would be nice to have `trash` similarly be a subcommand multiplexer, but still allow for `trash foo.txt` to call the `put` subcommand by default.

**Comment by andreafrancia** [comment]
What if you wanna trash a file named `empty`?

**Comment by pabs3** [comment]
The `trash` command could detect that its argument is both a file and a
subcommand then either exit with an error or alternatively assume that
the argument being a file overrides it being a subcommand and trash the
`empty` or `put` etc files. The first option would be safer and more
explicit, while the second option would be more compatible with the
current behaviour.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by andreafrancia** [comment]
I don't like the idea that a command change semantic according which file is in the file system.

**Comment by pabs3** [comment]
That was an idea for how to transition from the current trash command
to becoming solely a multiplexer. You could deprecate `trash file.txt`,
make it still work but print a warning and later remove it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
