### ISSUE TITLE
trash-empty fails for file with double quotes

### ISSUE THREAD

**Issue by WeakTopology** [andreafrancia/trash-cli#209]
**Describe the bug**
If I have a file in the trash with a double-quote in its name, trash-empty fails.

**trash-cli version**
```
$ trash-put --version
trash-put 0.21.6.30
```

**Operating system:**
 - OS: Arch Linux

**To Reproduce**
```
$ touch 'foo"'
$ trash-put 'foo"'
$ trash-list
2021-07-06 10:02:06 /home/username/foo"
$ trash-empty
/usr/local/bin/trash-empty: eval: line 57: unexpected EOF while looking for matching `"'
/usr/local/bin/trash-empty: eval: line 58: syntax error: unexpected end of file
```

**Expected behavior**
The trash should be emptied with no error.

**Additional information**
Files with a matching pair of double quotes also fail, but silently.
```
$ touch '"foo"'
$ trash-put '"foo"'
$ trash-list
2021-07-06 10:02:06 /home/username/"foo"
$ trash-empty
$ trash-list
2021-07-06 10:02:06 /home/username/"foo"
```

**Comment by andreafrancia** [comment]
Sorry but I can not reproduce you error:

```
# pacman -S trash-cli
....
# trash-put  --version
trash-put 0.21.6.30
# touch 'foo"'
# trash-put 'foo"'
# trash-list
2021-07-24 10:46:44 /root/foo"
# trash-empty
# 
```

Please send me the output of this command: `cat /usr/local/bin/trash-empty`.

**Comment by protist** [comment]
Thanks @andreafrancia. Ah right, good point. I forgot I was using a modified `trash-empty` to workaround issue #56. Looks like it's a bug in that code. I had a short attempt to try and fix it, but escaping quotes in nested bash statements is pretty confusing!

**Comment by WeakTopology** [comment]
Thanks @andreafrancia. Ah right, good point. I forgot I was using a modified trash-empty to workaround issue #56. Looks like it's a bug in that code. I had a short attempt to try and fix it, but escaping quotes in nested bash statements is pretty confusing!
