### ISSUE TITLE
trash-cli sends file to trash, but desktop icon doesn't reflect anything being there and doesn't offer empty trash option

### ISSUE THREAD

**Issue by jshtux** [andreafrancia/trash-cli#232]
**Describe the bug**
I ran trash somefile; then went to my desktop. The trash can icon stays looking like it it empty. When I right click on the trash can, the empty trash option is not available.

**trash-cli version**
Output of: trash-put --version
trash-put 0.22.4.16

**Operating system:**
 - OS: [e.g. Debian, Ubuntu, Fedora, macOs, Cygwin]
Mageia Linux 8

**To Reproduce**
Copy and paste the commands (and their output) to execute in order to reproduce 
the behavior:

$ touch foo
$ trash-put foo
$ ls foo
ls: cannot access 'foo': No such file or directory

$ trash-list
trash-list
2022-06-16 14:16:29 /home/jhatcher/Downloads/foo

**Expected behavior**
File shows up in trash-list, but desktop trash can icon does not show indication of anything being in trash and does not offer the empty trash option on right click.

**Comment by andreafrancia** [comment]
This is a problem of your Desktop Environment. It cannot be solved intervening on trash-cli.
Your desktop environment probably is not watching the filesystem for changes in the ~/.local/share/Trash/ directory.
I suggest you to ask assistance to your Desktop Environment.
