### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by rollingmoai** [andreafrancia/trash-cli#240]
**Is your feature request related to a problem? Please describe.**
It would be great if trash-cli has has support for Windows.

**Describe the solution you'd like**
Make it support Windows.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by andreafrancia** [comment]
I'm sorry but trash-cli does not support Windows.
You can find many solutions for Windows here: https://superuser.com/questions/24662/what-is-the-command-line-way-of-sending-files-to-the-recycle-bin
