### ISSUE TITLE
Hello, with `trash-cli 0.22.4.16`, installed from the NixOS package manager, it is now working properly on ZFS.

### ISSUE THREAD

**Issue by andreafrancia** [andreafrancia/trash-cli#243]
Hello, with `trash-cli 0.22.4.16`, installed from the NixOS package manager, it is now working properly on ZFS.

_Originally posted by @ejpcmac in https://github.com/andreafrancia/trash-cli/issues/242#issuecomment-1224170804_

**Comment by andreafrancia** [comment]
Hi @ejpcmac, thank you for your comment.
Can you install the latest version of trash-cli (0.22.8.21.16 at the time of writing)?
I don't know how and if the the NixOS package manager can download the latest version.

Using pip the command is:
```
pip install git+https://github.com/andreafrancia/trash-cli
```
After you have installed the latest version please send me some commands and their output that expose the problem you are facing.
If the problem is about volumes please send me also the output of these commands:
```
$ trash-list --version
$ trash-list --debug-volumes
$ trash-list --volumes
```
Thank you

**Comment by andreafrancia** [comment]
Sorry I was wrong, I did not read correctly. The problem was solved and I understood that it was still there.

**Comment by ejpcmac** [comment]
Hello, sorry not to have been reactive, I was on vacation part of the time and busy the remaining part. Anyway, thank you for fixing the issue, I am able to use `trash-cli` in `ranger` again 🙂
