### ISSUE TITLE
trash-put can't trash dangling symlinks

### ISSUE THREAD

**Issue by asklow** [andreafrancia/trash-cli#268]
**Describe the bug**
Can't delete symlinks that point to a non existing file/directory

**trash-cli version**
`0.22.10.20`

**Are you using the latest version of trash-cli?**
Yes

**Have you tried if the bug is present in the latest version of trash-cli?**
Yes

**Operating system:**
`archlinux/i3`

**To Reproduce**
```
$ ln -s foo bar          ## foo doesn't exist
$ trash-put bar
 trash-put: cannot trash symbolic link 'bar'
```
Now create `foo` & retry
```
$ touch foo
$ trash-put bar          ## will trash without an issue

**Comment by andreafrancia** [comment]
Thank you for you report, the issue has been fixed in commit 873c21be6259cf5d03efcac22816e89a7d0d394e
