### ISSUE TITLE
zsh tab-completion issues with external drives

### ISSUE THREAD

**Issue by grfrederic** [andreafrancia/trash-cli#278]
I'm using systemd to mount some external (network) drives. If they are not available, the completion hangs attempting to mount the drives, and even when they are available the completion ends up empty (I'm not sure why, it ends up empty even for my main drive...).

Is there a way to make trash-cli ignore these drives for tab suggestions? I already use the alias:
`alias tm="trash-put --trash-dir $TRASH_DIR" `
since I don't want to create Trash dirs on external drives, but that does not seem to stop completion from looking there.

**Comment by sprnza** [comment]
I don't think if it's resolved. I still experience the issue with the latest build.
