### ISSUE TITLE
Cannot trash file in /tmp

### ISSUE THREAD

**Issue by kleinbottle** [andreafrancia/trash-cli#28]
With `trash-put 0.11.3` packaged for Kubuntu 12.04, I am unable to `trash-put` a regular or empty file in `/tmp`.

When I run with `--verbose` on an empty file, I get this message:

```
trash-put: Failed to trash emptyfile in /.Trash/1000, because :topdir should be a directory: /.Trash/1000
trash-put: Failed to trash emptyfile in /.Trash-1000, because :[Errno 13] Permission denied: '/.Trash-1000'
trash-put: cannot trash regular empty file `emptyfile'
```

I have not tried this yet with the latest version and wanted to know if this sort of problem has already been fixed before I install the new version.

**Comment by andreafrancia** [comment]
1. This is a question for a security expert, maybe you can ask an answer on http://superuser.com/
2. trash-empty delete all files in all trash directories of your user without checking what your $PWD is.

**Comment by legolord208** [comment]
I think I'm having this same problem.
I made a partition for /, and a separate one for /home.

Now trash-cli refuses to let me trash files outside of /home!
Is there any way to fix this? I really don't wanna have a `/Trash` file in root...
