### ISSUE TITLE
zsh tab-completion of `trash-put` is broken

### ISSUE THREAD

**Issue by QuarticCat** [andreafrancia/trash-cli#280]
**Describe the bug**

When typing `trash-put -<TAB>`, the completion works. However, when typing `trash-put <TAB>` or `trash-put ./<TAB>`, I expect it to complete paths but it doesn't.

**trash-cli version**

0.22.10.20

**Are you using the latest version of trash-cli?**

Yes

**Operating system:**

 - OS: Arch

**Comment by ihasdapie** [comment]
Same issue. ALso on 0.22.10.20 and Arch.

**Comment by farfalleflickan** [comment]
Exact same, also on Arch.

**Comment by Horus645** [comment]
The issue I am having is similar, but not identical. `trash-put <TAB>` works once, for one file, and then it stops working. So it will only autocomplete for one item.

Also on arch, trash-put version 0.22.10.20

**Comment by cype-dev** [comment]
Installing trash-cli-git from the AUR fixed the problem for me.

**Comment by haselwarter** [comment]
Bump. Sounds like it's time for a new release.

**Comment by bd-g** [comment]
@andreafrancia Could you publish a new tag so package distribution can move to a working version?

**Comment by andreafrancia** [comment]
@bd-g Here https://github.com/andreafrancia/trash-cli/releases/tag/0.23.2.13.2

**Comment by yuannan** [comment]
> @bd-g Here https://github.com/andreafrancia/trash-cli/releases/tag/0.23.2.13.2

It's now fixed for me on :

Zsh: zsh 5.9 (x86_64-pc-linux-gnu)
OMZ: master (69b5737)

Thanks!

**Comment by bd-g** [comment]
@QuarticCat this is fixed for me as well, could probably close this issue?

**Comment by eriteric** [comment]
I am finally running trash-cli 0.23.2.13.2 from doing normal arch updates, and tab-completion freezes the terminal now. Any ideas? I've restarted and made sure the completions are there in /usr/share/zsh/site-functions/

trash-cli 0.23.2.13.2
zsh 5.9

**Comment by eriteric** [comment]
works ok now - not sure why
