### ISSUE TITLE
[Regression] trash-put no longer accept `--` to signal an end to option parsing

### ISSUE THREAD

**Issue by toonn** [andreafrancia/trash-cli#303]
**Describe the bug**
`trash-put` used to respect passing `--` as a sign to stop parsing arguments as options/flags. This is a convention among many CLI programs that have to deal with path arguments. Recent versions no longer respect this behavior.
[Ranger makes use of the `--` argument and users noticed this problem](https://github.com/ranger/ranger/issues/2858).

**trash-cli version**
Output of: trash-put --version

0.23.2.13.2 (as reported by the users)

**Are you using the latest version of trash-cli?**
Yes

**Have you tried if the bug is present in the latest version of trash-cli?**
Yes

**Please, install the latest version of trash-cli and try again before submitting the bug** :heavy_check_mark: 

Have done that? Then continue with the bug report.

**Operating system:**
 - OS: [e.g. Debian, Ubuntu, Fedora, macOs, Cygwin]
 -  Probably a Linux but not certain.

**To Reproduce**
Copy and paste the commands (and their output) to execute in order to reproduce 
the behavior:

$ touch -foo
$ trash-put -- -foo

**Expected behavior**
I hope this was an accidental regression and not an intended backwards-compatibility breaking change. [The output for `trash-put --help` still mentions the behavior](https://github.com/andreafrancia/trash-cli/blob/0.23.2.13.2/trashcli/put/parser.py#L57) so I have hope : )

**Comment by andreafrancia** [comment]
Right now I can't check, but if is confirmed it would be a unintended regression.

**Comment by xiota** [comment]
`trash` seems to treat `--` as a file.  Other arguments appear are moved to trash as expected.
```
$ trash --version
0.23.2.13.2

$ touch 1 2 3

$ ls
1  2  3

$ trash 3

$ ls
1  2

$ trash -- 2
trash: cannot trash non existent '--'

$ ls
1
```

**Comment by xiota** [comment]
Just built.  2b06075.  Works as expected.
```
$ touch 1 2 3

$ ls
1  2  3

$ trash -- 2 3

$ ls
1
```

**Comment by stelcodes** [comment]
Running into this issue too. I'm probably going to stop using this implementation.

**Comment by andreafrancia** [comment]
@stelcodes on my computer it works
```
$ pip install trash-cli
Collecting trash-cli
  Using cached trash_cli-0.23.9.23-py3-none-any.whl
Requirement already satisfied: psutil in ./env/lib/python3.11/site-packages (from trash-cli) (5.9.5)
Requirement already satisfied: six in ./env/lib/python3.11/site-packages (from trash-cli) (1.16.0)
Installing collected packages: trash-cli
Successfully installed trash-cli-0.23.9.23
$ touch pippo
$ trash-put -- pippo
$ ls pippo
ls: cannot access 'pippo': No such file or directory
```

Please be sure of using the latest version of trash-cli.
Run `trash -v` to verify your current version.
Beware that on some system trash could be an alias, a function, or another command different from trash-put.

**Comment by stelcodes** [comment]
@andreafrancia Yes you are right, I was using the previous version. Thanks for the update!
