### ISSUE TITLE
Add file trash location to the man page

### ISSUE THREAD

**Issue by joeljpa** [andreafrancia/trash-cli#307]
**Is your feature request related to a problem? Please describe.**
I always find myself opening the URL to this repo's README FAQ just to find the location of the trash files, when I do this like once in several months I guess.

**Describe the solution you'd like**
Why not just add it to the man page? 

> File trashed from the home partition will be moved here:
>~/.local/share/Trash/

**Describe alternatives you've considered**
Nothing. A simple proposition imo.

**Additional context**
Thanks a lot for this amazing utility!

**Comment by joeljpa** [comment]
PS: I can do a pull request if that's easier.

**Comment by andreafrancia** [comment]
I would be good for me.

**Comment by joeljpa** [comment]
Thanks! I've made a PR. Hope it's okay.
