### ISSUE TITLE
verbose output 

### ISSUE THREAD

**Issue by al-imam** [andreafrancia/trash-cli#317]
**Is your feature request related to a problem? Please describe.**
No it is not a problem. 

**Describe the solution you'd like**
i want a clear log of what is deleting but no information is login and no option i get for it sorry if the feature already exist but i can't find it. 

**Describe alternatives you've considered**
tash -v ...paths # show what is deleting relative path for nested files

**Additional context**
not required i think

**Comment by andreafrancia** [comment]
Can you provide more concrete examples that describes what trash-cli does now and what you want instead.
