### ISSUE TITLE
Configure trash folders

### ISSUE THREAD

**Issue by JPFrancoia** [andreafrancia/trash-cli#35]
Hi,

trash-cli is a great tool, but something bothers me. I have my / and my /home on different partitions. trash-cli correctly handles the partitions, i.e if I delete a file, it will put it in the directory .Trash on this partition.

But unfortunetaly, Nemo for instance puts the deleted files in a .Trash-1000. So, is there a way to tell trash-cli how it should name the trash folder ?

Thanks

**Comment by a3nm** [comment]
I second this, it would be great to have a CLI parameter to force the location of the trash. My use case is that I want my trash to always reside on my home folder no matter on which filesystem the files were deleted, and I don't see how I could configure this...

**Comment by msx** [comment]
Hello all, another +1 to this feature, here is my use case:
At work I manage a poorly-partitioned server on which I would like to manually choose the location of the trash directory.
Cheers.

**Comment by potherca** [comment]
:+1: Sounds like a sensible proposal! :smile_cat:

**Comment by andreafrancia** [comment]
With commit d34551f7a5574aef2c3b9eccff2b94c0c4e890ed trash-put learned a --trash-dir option that can be used to specify the trash directory to be used as destination.

You can force the use of a specific trash typing:

```
trash-put --trash-dir /.Trash-1000 file-to-be-trashed
```

Please check it out and tell if it works for you.

**Comment by a3nm** [comment]
Thanks for this change! I can test it when there is a new version of trash-cli that gets shipped with Debian and features the change.

**Comment by Anagastes** [comment]
> With commit [d34551f](https://github.com/andreafrancia/trash-cli/commit/d34551f7a5574aef2c3b9eccff2b94c0c4e890ed) trash-put learned a --trash-dir option that can be used to specify the trash directory to be used as destination.
> 
> You can force the use of a specific trash typing:
> 
> ```
> trash-put --trash-dir /.Trash-1000 file-to-be-trashed
> ```
> 
> Please check it out and tell if it works for you.

I have now compiled the version because the Distris simply do not record it.

The variable works quite well, but you can't view this data with "trash-list", the default folder is always used.

So the variable would have to be implemented for the other functions as well. :)
