### ISSUE TITLE
trash-restore not found

### ISSUE THREAD

**Issue by ElijahLynn** [andreafrancia/trash-cli#43]
Installed at beginning of the week and could have sworn I saw trash-restore, went to go use it and "command not found". Tried reinstalling the Python way and no go. Should I reinstall?

**Comment by kcassam** [comment]
Readme file has not be updated

**Comment by ElijahLynn** [comment]
@kcassam The readme appears to be correct, it is just that there hasn't been a new tag since it was changed and the `trash-restore` is in master branch only. If you check out the latest tag the readme says `restore-trash`. 

https://github.com/andreafrancia/trash-cli/tree/0.12.9.14
