### ISSUE TITLE
ReST typo in README.rst

### ISSUE THREAD

**Issue by dpbmm** [andreafrancia/trash-cli#49]
See the screenshot below:

![screen shot 2015-02-22 at 12 18 05](https://cloud.githubusercontent.com/assets/9936349/6319528/f7605c50-ba8c-11e4-893b-b99eade3cc3f.png)

I am reading GitHub on Firefox 35.0.1.

**Comment by andreafrancia** [comment]
I think this was already solved sometime ago. Please feel free to re-open the issue otherwise.
