### ISSUE TITLE
Allow "trash-restore $path"

### ISSUE THREAD

**Issue by anntzer** [andreafrancia/trash-cli#54]
... easier than having to scroll through a long list of paths.
Another option would be at least to sort the restorable paths.

**Comment by Link-Satonaka** [comment]
Let's not burden the dev with things that are built into linux- we can already sort restorable paths. The `colrm` command is, afaik, part of the core system utils on all linux distros. It removes a range of "columns" from text output. The `trash-list` command outputs 20 columns for the date and timestamp (might be different on your system if you don't use 24h time), so we can eliminate the timestamp using colrm to just get an output of absolute paths.
`$ trash-list | colrm 1 20`
The `sort` command is also, afaik, part of the core system utils for all linux distros. Read its manpage to learn about different sorting methods, but for the purpose of sorting by path:
`$ trash-list | colrm 1 20 | sort`

That just leaves the feature request: `trash-restore [pattern]`. You could easily specify a path as your pattern.

**Comment by andy5995** [comment]
> Let's not burden the dev with things that are built into linux- we can already sort restorable paths.

Agreed, @Link-Satonaka

**Comment by mhalano** [comment]
I agree with this problem. I want to (not) to do this:
trash-put <file>
And after that:
trash-restore !^
But because trash-restore just shows a menu, it's become impossible.

**Comment by andreafrancia** [comment]
I've implemented a sort of `trash-restore [pattern]`, in this commit 421bf25cc5d65d711cf91d2b64a0f9c766738476 .
Please try out and let me know if it is going in the right directory.

Thank you.

**Comment by andreafrancia** [comment]
I'm closing this issue, feel free to comment or reopen as you find something to add or fix.
