### ISSUE TITLE
Problem using Trash on a usb key

### ISSUE THREAD

**Issue by dummys** [andreafrancia/trash-cli#59]
When using rm on a usb key and after typing trash-list I got this error:

TrashDir skipped because parent not sticky: /backup/.Trash/1000
TrashDir skipped because parent not sticky: /mnt/usbkey/disk2go2/.Trash/1000

**Comment by andreafrancia** [comment]
To solve the problem make these directories sticky:

/backup/.Trash
/mnt/usbkey/disk2go2

I may want lookup the 'chmod' man page to discover what is the exact flag to pass to chmod to do this, unfortunately right now I don't remember it.

**Comment by iangreenleaf** [comment]
`sudo chmod +t /backup/.Trash` replacing the dir name as needed.

However, this doesn't solve the problem for trash dirs on file systems that don't persist Unix permissions. I'm having this issue with an NTFS drive, and I imagine VFAT has the same problems.
