### ISSUE TITLE
Why not support search function for trash-restore

### ISSUE THREAD

**Issue by wuyihao14** [andreafrancia/trash-cli#60]
Why not support search function for trash-restore? It's really a pain to seek through the list. Maybe it's an alternative to support grep.

**Comment by andreafrancia** [comment]
Pleas try the latest version of trash-cli, it supports (in alpha) passing a path to trash-restore to restrict the output of trash-restore.

**Comment by iceqing** [comment]
Why not support search function for trash-restore now?
