### ISSUE TITLE
trash-restore all/multiple files

### ISSUE THREAD

**Issue by krompus** [andreafrancia/trash-cli#63]
I just accidentally trashed my massive downloads folder; I had all the files in the folder selected within `ranger`, and tried to delete a single file, forgetting they were all selected.

Derp.

So, I got everything back, but I had to `$ trash-restore` `0` <CR> 200 times, manually.

It would be really nice to have a method of restoring multiple files at once, or perhaps just an option to restore ALL files at once. in case something like this happens.

**Comment by andreafrancia** [comment]
while ( echo '0' | trash-restore ) ; do true; done;

**Comment by krompus** [comment]
Awesome; thanks!

This works perfectly for the issue described above, in that it only functions on the pwd. Would there happen to be a command to restore all files regardless of directory?

**Comment by andreafrancia** [comment]
I never tested it, please use caution:

(cd / && while ( echo '0' | trash-restore ) ; do true; done; )

**Comment by krompus** [comment]
Thanks again!

**Comment by senft** [comment]
I think it would be much more flexible, to allow users to enter multiple indices at once. Some programs allow that by entering `1-3 7 10-12`, which would be parsed to `[1,2,3,7,10,11,12]`.

**Comment by et304383** [comment]
Why doesn't it just take a * to restore all files?

**Comment by Archie-2021** [comment]
Is there a update on this? I think the ability to choose an array of indexes is a nice option to have instead of just choosing one.

**Comment by andreafrancia** [comment]
@Archie-2021 
> Is there a update on this? I think the ability to choose an array of indexes is a nice option to have instead of just choosing one.

This is already implemented:

Restore multiple trashed files separated by ',', also support range::

    $ trash-restore
    0 2007-08-30 12:36:00 /home/andrea/foo
    1 2007-08-30 12:39:41 /home/andrea/bar
    2 2007-08-30 12:39:41 /home/andrea/bar2
    3 2007-08-30 12:39:41 /home/andrea/foo2
    What file to restore [0..3]: 0-2, 3
    $ ls foo bar bar2 foo2
    foo bar bar2 foo2

**Comment by Archie-2021** [comment]
> @Archie-2021
> 
> > Is there a update on this? I think the ability to choose an array of indexes is a nice option to have instead of just choosing one.
> 
> This is already implemented:
> 
> Restore multiple trashed files separated by ',', also support range::
> 
> ```
> $ trash-restore
> 0 2007-08-30 12:36:00 /home/andrea/foo
> 1 2007-08-30 12:39:41 /home/andrea/bar
> 2 2007-08-30 12:39:41 /home/andrea/bar2
> 3 2007-08-30 12:39:41 /home/andrea/foo2
> What file to restore [0..3]: 0-2, 3
> $ ls foo bar bar2 foo2
> foo bar bar2 foo2
> ```

Weird, I am kinda sure was trying something like that to send it an input as an arrays and it didn't work, but now that I am trying again it is working fine.

Thanks

**Comment by ease-zh** [comment]
![image](https://github.com/andreafrancia/trash-cli/assets/28568749/4cdfb5dc-e1c3-4654-b69e-592bb4d345d2)
Never succeeded in restoring multiple files, always raise Invalid entry, anyone know why?

**Comment by andreafrancia** [comment]
> ![image](https://user-images.githubusercontent.com/28568749/273356979-4cdfb5dc-e1c3-4654-b69e-592bb4d345d2.png) Never succeeded in restoring multiple files, always raise Invalid entry, anyone know why?

Please use this page to add a new issue and be careful to follow the instructions about updating your version of trash-cli.
