### ISSUE TITLE
Change trash folder to user home

### ISSUE THREAD

**Issue by czuee** [andreafrancia/trash-cli#66]
How can I change the trash folder from /Home/.Trash to /home/user/.Trash. 

I do not have permission to change the root directory, but I want to use the trash for my own account.

**Comment by andy5995** [comment]
@czuee I tried this with version 0.12.9.14
I see it defaults to $HOME and uses $HOME/.local/share/Trash

You're having trouble using it from a non-root account?

**Comment by andreafrancia** [comment]
@czuee can you elaborate a bit more on your problem?
