### ISSUE TITLE
How to Force trash-cli to use a top level .Trash dir

### ISSUE THREAD

**Issue by ihipop** [andreafrancia/trash-cli#70]
How to Force trash-cli to use a top level `.Trash` dir
I don't want to store trash in `~/.local/share/Trash/` in root partition

**Comment by andreafrancia** [comment]
Try to the following:
* remove ~/.local/share/Trash/
* `touch ~/.local/share/Trash`

Now, if I remember well, `trash-put` should fallback to `/.Trash/$uid` or `/.Trash-$uid`
Reopen this issue if it does not work.

**Comment by ihipop** [comment]
it works.
Thanks for your great work

**Comment by p1r473** [comment]
This worked for me
```
rm -rf ~/.local/share/Trash/
touch ~/.local/share/Trash
```
