### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by Brottweiler** [andreafrancia/trash-cli#73]
The latest [release](https://github.com/andreafrancia/trash-cli/releases) was 4 years ago, and you just pushed a new version in https://github.com/andreafrancia/trash-cli/commit/36ae6da9a0d3342aeaa28660369419aa86ddbe22. Why not make it a release?

**Comment by andreafrancia** [comment]
Now [release](https://github.com/andreafrancia/trash-cli/releases) shows the tag for the version of yesterday and for the day before.
