### ISSUE TITLE
debian etc packaging ?

### ISSUE THREAD

**Issue by DrupaListo-com** [andreafrancia/trash-cli#74]
Hi, do we have some build scripts or system for debian packaging in place?

What is needed besides from building the debs to push them to the official debian repos?

**Comment by andreafrancia** [comment]
I think that those question should be asked directly to Debian maintainers.
Here I found a page where you can report bug about trash-cli in Debian: https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=trash-cli
