### ISSUE TITLE
trash-cli creates a new .Trash directory also a ~/.local/share/Trash exists

### ISSUE THREAD

**Issue by octavsly** [andreafrancia/trash-cli#8]
In the / directory I have a link 
home -> /mnt/store/home

If I use trash, the ~/.local/share/Trash is not used but rather a new trash directory is created at /mnt/store/.Trash/500
However trash-list seems to look at ~/.local/share/Trash

Furthermore it complains about sticky bits. Why trash-cli is not correcting the rights? at least for directories which are created. 

Overall, a very useful command line trash.

Best regards,
Octavian

**Comment by JohnRobson** [comment]
This bug persists:

`trash-put: found unsecure .Trash dir (should be sticky): /tmp/.Trash
trash-put: `test' trashed in /tmp/.Trash/1000`

I have: "/tmp/.Trash", "/tmp/.Trash-1000", "/tmp/.Trash/1000", "/tmp/Trash", etc...
