### ISSUE TITLE
update trash-cli package for debian

### ISSUE THREAD

**Issue by Zurd** [andreafrancia/trash-cli#86]
The Debian package of trash-cli is 0.12.9.14 which is an old version and I have a bug with it. I had to manually install trash-cli instead of just running "apt install trash-cli".

Would it be possible to update the one on Debian?

Here's what I could find:
https://packages.debian.org/jessie/trash-cli
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=trash-cli;dist=unstable

Just not sure how to proceed next.

Cheers,

**Comment by andreafrancia** [comment]
Sorry, but the Debian packaging is something out of my control.
I keep up-to-date only the code on GitHub and the releases on PyPI: https://pypi.python.org/pypi/trash-cli
The packaging of Debian and other distribution is done by other peoples working or volunteering for that distribution.

I think you can report a bug in the Debian following the instruction listed in https://www.debian.org/Bugs/Reporting and asking for an update.

Please note that once you have pip (apt install pip) installing the up-to-date version from PyPI should be pretty automated:

```
sudo apt install python-pip
pip install trash-cli --user
```

**Comment by Zurd** [comment]
Thanks for the info, I've reported it:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=856814
