### ISSUE TITLE
man trash-list claims it takes a `[PATH]...` argument?

### ISSUE THREAD

**Issue by Poddster** [andreafrancia/trash-cli#87]
The [man page](https://github.com/andreafrancia/trash-cli/blob/master/man/man1/trash-list.1#L24) for `trash-list` claims it takes a `[PATH]...` argument. But trying it out it doesn't seem to do anything!

Checking [the source](https://github.com/andreafrancia/trash-cli/blob/master/trashcli/list.py#L33) it doesn't look like `on_argument_action` is called, which would be required for it to do "something" with the rest of argv.

I imagine it's just a typo in the man page and you don't intend to do anything with the path? (If so: should you not also error on extra arguments given that you haven't processed?)

Thanks

**Comment by andreafrancia** [comment]
You're right. Thanks for reporting.
