### ISSUE TITLE
Can't trash regular file

### ISSUE THREAD

**Issue by alqh** [andreafrancia/trash-cli#9]
Hi,

I'm trying to trash a file stored in the mounted drive /media/NameOfMyDrive.

eg.

$ touch something
$ trash-put something
trash-put: cannot trash regular file `something'

It works on home directory, but doesn't on a mounted drive. 
Drive is exFat, and a .Trash-<some uid> is present in the drive. 
Maybe it has something to do with the permission of /media, although to create, delete file from mount doesn't require the admin permission

**Comment by bnaman50** [comment]
Hey @andreafrancia , I am facing the similar issue. 

When I use `trash-put` in my home directory, it works perfectly as you can see 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/5251592/189554225-5d79a7bd-d4f8-401a-bce2-f8e14788eb34.png">

However, we have another disk `\data` and `trash-put` command does not work there. 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/5251592/189554269-a71552e9-59bb-46bd-bfa3-07c2f30a00c8.png">

I have created a `.Trash-$UID` dir and provided the permissions as mentioned in the documentation
```chmod a+rw .Trash-$UID`
chmod +t .Trash-$UID```

I am not sure what to do. Could you please help me out?

Thanks, 
Naman
