### ISSUE TITLE
trash-* returns segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cseanburns** [andreafrancia/trash-cli#90]
I'm receiving a "Segmentation fault (core dumped)" while using some of the trash commands. The basic `trash` command works without receiving any errors (e.g., `trash file.txt`), but when running `trash-empty` or `trash-list`, I receive the segmentation error even though `trash` does the job (confirmed by examining $HOME/.local/share/Trash/).

    ~: trash-list
    2017-02-27 12:03:47 /home/sean/newfile.txt
    2017-02-27 12:02:24 /home/sean/file.txt
    Segmentation fault (core dumped)
    ~: trash-empty
    Segmentation fault (core dumped)
    ~: trash-list
    Segmentation fault (core dumped)

Trash was installed via the repos and I'm running the i3 window manager on:

    ~: cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.10
    DISTRIB_CODENAME=yakkety
    DISTRIB_DESCRIPTION="Ubuntu 16.10"
    ~: uname -a
    Linux ncc1701f 4.8.0-39-generic #42-Ubuntu SMP Mon Feb 20 11:47:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    ~: trash --version
    trash 0.12.9.14

I can't test this right now, but for some reason I recall that the error didn't reproduce while logged in under Unity instead of i3.

**Comment by jaccarmac** [comment]
I can dupe this on Gentoo/KDE. Same deal as in #52 though I won't speculate as to the root cause: All commands work but dump core at the end.

**Comment by andreafrancia** [comment]
Please let me know if it’s still a thing.
