### ISSUE TITLE
Cygwin Python3.6：trash-list trash-empty trash-rm all raise TypeError: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by samegek** [andreafrancia/trash-cli#92]
> Administrator@USER-20170304SB ~
> $ trash-list
> 2017-04-20 20:59:08 /home/Administrator/hello
> Traceback (most recent call last):
>   File "/usr/bin/trash-list", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/trashcli/cmds.py", line 51, in list
>     ).run(*sys.argv)
>   File "/usr/lib/python3.6/site-packages/trashcli/list.py", line 37, in run
>     parse(argv)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 110, in __call__
>     self.default_action()
>   File "/usr/lib/python3.6/site-packages/trashcli/list.py", line 51, in list_trash
>     trashdirs.list_trashdirs()
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 151, in list_trashdirs
>     self._for_each_volume_trashcan()
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 158, in _for_each_volume_trashcan
>     self.emit_trashcans_for(volume)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 160, in emit_trashcans_for
>     self.emit_trashcan_1_for(volume)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 163, in emit_trashcan_1_for
>     top_trashdir_path = os.path.join(volume, '.Trash/%s' % self.getuid())
>   File "/usr/lib/python3.6/posixpath.py", line 92, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
>     raise TypeError("Can't mix strings and bytes in path components") from None
> TypeError: Can't mix strings and bytes in path components

> $ trash-empty
> Traceback (most recent call last):
>   File "/usr/bin/trash-empty", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/trashcli/cmds.py", line 39, in empty
>     ).run(*argv)
>   File "/usr/lib/python3.6/site-packages/trashcli/empty.py", line 48, in run
>     parse(argv)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 110, in __call__
>     self.default_action()
>   File "/usr/lib/python3.6/site-packages/trashcli/empty.py", line 83, in empty_all_trashdirs
>     trashdirs.list_trashdirs()
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 151, in list_trashdirs
>     self._for_each_volume_trashcan()
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 158, in _for_each_volume_trashcan
>     self.emit_trashcans_for(volume)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 160, in emit_trashcans_for
>     self.emit_trashcan_1_for(volume)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 163, in emit_trashcan_1_for
>     top_trashdir_path = os.path.join(volume, '.Trash/%s' % self.getuid())
>   File "/usr/lib/python3.6/posixpath.py", line 92, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
>     raise TypeError("Can't mix strings and bytes in path components") from None
> TypeError: Can't mix strings and bytes in path components

> Administrator@USER-20170304SB ~
> $ trash-rm hello
> Traceback (most recent call last):
>   File "/usr/bin/trash-rm", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.6/site-packages/trashcli/rm.py", line 69, in main
>     cmd.run(sys.argv)
>   File "/usr/lib/python3.6/site-packages/trashcli/rm.py", line 49, in run
>     trashdirs.list_trashdirs()
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 151, in list_trashdirs
>     self._for_each_volume_trashcan()
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 158, in _for_each_volume_trashcan
>     self.emit_trashcans_for(volume)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 160, in emit_trashcans_for
>     self.emit_trashcan_1_for(volume)
>   File "/usr/lib/python3.6/site-packages/trashcli/trash.py", line 163, in emit_trashcan_1_for
>     top_trashdir_path = os.path.join(volume, '.Trash/%s' % self.getuid())
>   File "/usr/lib/python3.6/posixpath.py", line 92, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
>     raise TypeError("Can't mix strings and bytes in path components") from None
> TypeError: Can't mix strings and bytes in path components
>

**Comment by samegek** [comment]
if useing py2, it works.

**Comment by andreafrancia** [comment]
I don't have access to a cygwin system, so I can't reproduce this bug. Please try the more recent version maybe it fixed the problem.
Install it using `pip`:
```
pip install trash-cli
```
