### ISSUE TITLE
[Enhancement] trash-empty should have --dry-run and --verbose options

### ISSUE THREAD

**Issue by fastcat** [andreafrancia/trash-cli#93]
The trash-empty command ought to have a `--dry-run` option that causes it to only print what it would empty without actually emptying it, and a `--verbose` option that prints what it is removing as it goes.

**Comment by landerlo** [comment]
I agree it would be very useful. I'm happy to create the PR for this if @andreafrancia is still willing to review and consider a PR for this feature.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
@andreafrancia This Issue is quite old. Does @landerlo still want to provide an PR for this? We need an answer from @andreafrancia first if this would be accepted.

**Comment by andreafrancia** [comment]
I cannot say if a Pull Request will be accepted before seeing it. You don't need me to add a functionality to trash-cli just fork it, implements what you think is needed and use PR and issues to let other people know your version exists. If the patch is worth it will be eventually incorporated in this project.

**Comment by andreafrancia** [comment]
Implemented in f5d3b34 and in 31954e2.
