### ISSUE TITLE
Changing default Python version from 2 to 3 breaks installation on Fedora

### ISSUE THREAD

**Issue by xileF1337** [andreafrancia/trash-cli#94]
Hi,

I'm using the repository version of trash-cli on a Fedora 25 workstation. Recently, I changed my default Python version from 2 to 3. Since then, running e. g. trash-put causes an error:

~~~
Traceback (most recent call last):
  File "/usr/bin/trash-put", line 4, in <module>
    from trashcli.put import main as main
ImportError: No module named 'trashcli'
~~~

The reason seems to be that the python modules used by trashcli are installed into the python2 directories:

~~~
dnf repoquery -l trash-cli
Last metadata expiration check: 17:32:05 ago on Tue Jun 27 15:35:09 2017.
/usr/bin/trash
/usr/bin/trash-empty
/usr/bin/trash-list
/usr/bin/trash-put
/usr/bin/trash-restore
/usr/bin/trash-rm
/usr/lib/python2.7/site-packages/trash_cli-0.12.10.3_-py2.7.egg-info
/usr/lib/python2.7/site-packages/trashcli
/usr/lib/python2.7/site-packages/trashcli/__init__.py
/usr/lib/python2.7/site-packages/trashcli/__init__.pyc
/usr/lib/python2.7/site-packages/trashcli/__init__.pyo
/usr/lib/python2.7/site-packages/trashcli/cmds.py
/usr/lib/python2.7/site-packages/trashcli/cmds.pyc
/usr/lib/python2.7/site-packages/trashcli/cmds.pyo
/usr/lib/python2.7/site-packages/trashcli/fs.py
/usr/lib/python2.7/site-packages/trashcli/fs.pyc
/usr/lib/python2.7/site-packages/trashcli/fs.pyo
/usr/lib/python2.7/site-packages/trashcli/fstab.py
/usr/lib/python2.7/site-packages/trashcli/fstab.pyc
/usr/lib/python2.7/site-packages/trashcli/fstab.pyo
/usr/lib/python2.7/site-packages/trashcli/list_mount_points.py
/usr/lib/python2.7/site-packages/trashcli/list_mount_points.pyc
/usr/lib/python2.7/site-packages/trashcli/list_mount_points.pyo
/usr/lib/python2.7/site-packages/trashcli/put.py
/usr/lib/python2.7/site-packages/trashcli/put.pyc
/usr/lib/python2.7/site-packages/trashcli/put.pyo
/usr/lib/python2.7/site-packages/trashcli/rm.py
/usr/lib/python2.7/site-packages/trashcli/rm.pyc
/usr/lib/python2.7/site-packages/trashcli/rm.pyo
/usr/lib/python2.7/site-packages/trashcli/trash.py
/usr/lib/python2.7/site-packages/trashcli/trash.pyc
/usr/lib/python2.7/site-packages/trashcli/trash.pyo
/usr/share/doc/trash-cli
/usr/share/doc/trash-cli/README.rst
/usr/share/man/man1/trash-empty.1.gz
/usr/share/man/man1/trash-list.1.gz
/usr/share/man/man1/trash-put.1.gz
/usr/share/man/man1/trash-restore.1.gz
/usr/share/man/man1/trash-rm.1.gz
~~~

A way to fix this would be to explicitly ask for the python2/3 interpreter in the shebang line of the top-level scripts `usr/bin/trash*`, i.e change the first line to `#!/usr/bin/python2` or `#!/usr/bin/python3`
 depending on the python version for which the backend module was installed. Shouldn't this be part of the regular setup / package installation routine?

**Comment by ari3s** [comment]
Which trash-cli version have you installed? Python 3 is supported in Fedora in trash-cli since version 0.17.1.14 which will be available in Fedora 26.

**Comment by xileF1337** [comment]
Sorry for the missing info, it's version 0.12.9.14 of trash-cli (that is the most up-to-date one from the repositories). Now I see that the repository version is lagging somewhat behind. Great if the up-to-date version fixes the issue (I assume that the Fedora package will install both the Python 2 and Python 3 libraries?). Thank you.

**Comment by jxu** [comment]
I have the same issue after upgrading to Ubuntu 20.04 LTS. I fixed it by uninstalling, removing ~/.local/bin/trash*, then reinstalling.
