### ISSUE TITLE
restore-trash should sort

### ISSUE THREAD

**Issue by emotionally-exhausted** [andreafrancia/trash-cli#98]
restore-trash should sort the list of files in trash to make it easier to locate the file you're looking for, especially if you don't remember the exact name.

**Comment by hrsma2i** [comment]
https://github.com/andreafrancia/trash-cli/issues/117

**Comment by santids** [comment]
trash-list | sort -k3 (sorts by path)

**Comment by santids** [comment]
Try this `echo q | trash-restore | sort -k4`

**Comment by Self-Perfection** [comment]
Also we should be able to sort by deletion date as well as by path. Yeah, we can pre-sort as @santids suggested: `echo q | trash-restore | sort -k2,3` but still this is less convenient.
